services:
  - type: web
    name: truth-scaffold-web
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements-web.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: PG_DSN
        sync: false
